[package]
name = "office-next"
version = "2026.1008.2255"
edition = "2021"
license = "Apache-2.0"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-single-instance = "~2.4.5"
tauri-plugin-dialog = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-global-shortcut = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
notify = "8"
walkdir = "2"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["time", "macros", "sync"] }
keyring = { version = "3", features = ["windows-native"] }
tempfile = "3"
uuid = { version = "1", features = ["v4"] }
open = { version = "5", features = ["shellexecute-on-windows"] }
regex = "1"
sha2 = "0.10"
base64 = "0.22"
chrono = { version = "0.4", default-features = false, features = ["std", "clock"] }
serde_yaml = "0.9"

[target.'cfg(windows)'.dependencies]
winreg = "0.55"
tauri-winrt-notification = "0.8.1"
windows = { version = "0.62", features = ["UI_Notifications"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
strip = true
