import type { PricingConfig, PricingRule, Proposal } from './types';
import { hasPricingChange } from './assistantPricing';
const pricingLabels:Partial<Record<keyof PricingRule,string>>={modelIds:'模型 ID / 别名',providerHost:'服务域名',currency:'币种',inputPerMillion:'未缓存输入 / 百万 token',cachedInputPerMillion:'缓存输入 / 百万 token',outputPerMillion:'输出 / 百万 token',schedule:'计费时段',offPeakDiscount:'空闲时段折扣',source:'计价来源',verifiedAt:'核对日期'};
function pricingValue(v:unknown):string{if(v===undefined)return '无';if(Array.isArray(v))return v.join('、')||'无';if(v==='flat')return '固定单价';if(v==='deepseek')return 'DeepSeek 峰谷时段';return String(v);}
function PricingDiff({before,after}:{before?:PricingConfig;after?:PricingConfig}){
  const ids=[...new Set([...(before?.rules||[]),...(after?.rules||[])].map(r=>r.id))];
  const years=[...new Set([...Object.keys(before?.holidays||{}),...Object.keys(after?.holidays||{})])].filter(y=>JSON.stringify(before?.holidays[y])!==JSON.stringify(after?.holidays[y]));
  return <div className="pricing-diff">{ids.map(id=>{const old=before?.rules.find(r=>r.id===id),next=after?.rules.find(r=>r.id===id);const keys=(Object.keys(pricingLabels) as (keyof PricingRule)[]).filter(k=>JSON.stringify(old?.[k])!==JSON.stringify(next?.[k]));return keys.length?<div className="markdown-table" key={id}><table><caption>{(next||old)?.modelIds.join(' / ')} · {old?next?'调整':'移除':'新增'}</caption><thead><tr><th>计价项目</th><th>当前</th><th>调整后</th></tr></thead><tbody>{keys.map(k=><tr key={k}><th>{pricingLabels[k]}</th><td>{pricingValue(old?.[k])}</td><td>{pricingValue(next?.[k])}</td></tr>)}</tbody></table></div>:null;})}{years.map(year=><div className="pricing-calendar-diff" key={year}><strong>{year} 年节假日调整</strong><div><p>当前：{pricingValue(before?.holidays[year])}</p><p>调整后：{pricingValue(after?.holidays[year])}</p></div></div>)}</div>;
}
export const configurationLabels:Record<string,string>={roots:'搜索目录',theme:'主题',recursive:'包含子目录',filter:'默认筛选',launchers:'快捷工具',assistantReasoning:'助手思考程度',translationReasoning:'翻译思考程度',assistantOutputTokens:'助手输出上限',translationOutputTokens:'翻译输出上限',modelRequestTimeoutSecs:'请求总预算（秒）',modelFirstResponseTimeoutSecs:'首响应等待（秒）',modelIdleTimeoutSecs:'输出停滞等待（秒）',assistantTaskTimeoutSecs:'任务总预算（秒）',modelRetryCount:'重试次数',assistantHistoryMessages:'历史消息条数',assistantHistoryChars:'每条历史长度',assistantToolRounds:'模型执行轮数',assistantSearchLimit:'联网搜索次数',assistantAutoContinue:'截断后续写',assistantContinueTokens:'续写输出上限',modelContextTokens:'上下文容量',modelTemperature:'温度',modelTopP:'采样范围'};
function value(v:unknown):string{if(v==null)return '模型默认';if(typeof v==='boolean')return v?'开启':'关闭';if(typeof v==='string')return ({max:'最大',ultra:'最大',high:'高',low:'低',none:'关闭思考',default:'模型默认',light:'浅色',dark:'深色',system:'跟随系统'} as Record<string,string>)[v]||v;if(Array.isArray(v))return v.map(x=>typeof x==='string'?x:`${x.name}：${x.path}`).join('\n')||'无';return String(v);}
export function ProposalDiff({proposal}:{proposal:Proposal}){
  const rows=Object.keys(configurationLabels).filter(k=>JSON.stringify(proposal.before[k as keyof Proposal['before']])!==JSON.stringify(proposal.after[k as keyof Proposal['after']]));
  const pricingChanged=hasPricingChange(proposal);
  return <div className="proposal-diff">{proposal.reason&&<div className="proposal-reason"><strong>调整建议</strong><p>{proposal.reason}</p></div>}{proposal.impact&&<p className="proposal-impact">调整影响：{proposal.impact}</p>}{pricingChanged&&<PricingDiff before={proposal.before.modelPricing} after={proposal.after.modelPricing}/>} {!!rows.length&&<div className="markdown-table"><table><thead><tr><th>调整项目</th><th>当前配置</th><th>调整后</th></tr></thead><tbody>{rows.map(k=><tr key={k}><th>{configurationLabels[k]}</th><td>{value(proposal.before[k as keyof Proposal['before']])}</td><td>{value(proposal.after[k as keyof Proposal['after']])}</td></tr>)}</tbody></table></div>}{!rows.length&&!pricingChanged&&<p>没有需要更改的项目。</p>}</div>;
}
